local: &local
  adapter: mysql
  username: root
# host: 127.0.0.1 # Uncomment to fix OSX could not connect to socket
  password:
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  database: pbook_dev
  <<: *local

test: &test
  database: pbook_test
  <<: *local

cucumber:
  <<: *test

staging:
  database: pbook_staging
  <<: *local

production:
  database: pbook_prod
  <<: *local
